# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panes.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_panesWindow(object):
    def setupUi(self, panesWindow):
        panesWindow.setObjectName(_fromUtf8("panesWindow"))
        panesWindow.resize(803, 599)
        self.centralwidget = QtGui.QWidget(panesWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.checkBox_4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(650, 260, 101, 31))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 330, 171, 61))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.checkBox_6 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(650, 340, 101, 31))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 150, 171, 41))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 260, 171, 61))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 220, 171, 61))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(680, 30, 71, 101))
        self.pushButton_6.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("la-flecha-azul-al-lado-de-icono-5057-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.checkBox_5 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(650, 300, 101, 31))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(650, 150, 101, 31))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 180, 171, 61))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 40, 311, 71))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("UTEC.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(650, 190, 101, 31))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 150, 191, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 30, 81, 101))
        self.pushButton_2.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("flecha-hacia-la-izquierda-antes-de-icono-4330-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 290, 171, 61))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(650, 230, 101, 31))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 310, 191, 31))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 270, 191, 31))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 230, 191, 31))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 190, 191, 31))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 390, 191, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 350, 191, 31))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 370, 171, 61))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.checkBox_7 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(650, 380, 101, 31))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        panesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(panesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMENUTEC = QtGui.QMenu(self.menubar)
        self.menuMENUTEC.setObjectName(_fromUtf8("menuMENUTEC"))
        panesWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(panesWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        panesWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMENUTEC.menuAction())

        self.retranslateUi(panesWindow)
        QtCore.QMetaObject.connectSlotsByName(panesWindow)

    def retranslateUi(self, panesWindow):
        panesWindow.setWindowTitle(_translate("panesWindow", "MainWindow", None))
        self.checkBox_4.setText(_translate("panesWindow", "10.00", None))
        self.label_6.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.checkBox_6.setText(_translate("panesWindow", "6.00", None))
        self.label.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.label_4.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.label_3.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.checkBox_5.setText(_translate("panesWindow", "8.00", None))
        self.checkBox.setText(_translate("panesWindow", "12.00", None))
        self.label_2.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.pushButton.setText(_translate("panesWindow", "SANDWICHES, JUGOS Y BEBIDAS", None))
        self.checkBox_2.setText(_translate("panesWindow", "10.00", None))
        self.pushButton_3.setText(_translate("panesWindow", "Mixto Completo Caliente", None))
        self.label_5.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.checkBox_3.setText(_translate("panesWindow", "12.00", None))
        self.pushButton_4.setText(_translate("panesWindow", "Chorizo", None))
        self.pushButton_10.setText(_translate("panesWindow", "Filete De Pollo", None))
        self.pushButton_11.setText(_translate("panesWindow", "Pan C/ Pollo", None))
        self.pushButton_12.setText(_translate("panesWindow", "Hamburguesa Pollo/Carne", None))
        self.pushButton_5.setText(_translate("panesWindow", "Triple Varios", None))
        self.pushButton_8.setText(_translate("panesWindow", "Croissant", None))
        self.label_7.setText(_translate("panesWindow", "(Descripcion del menú )", None))
        self.checkBox_7.setText(_translate("panesWindow", "6.00", None))
        self.menuMENUTEC.setTitle(_translate("panesWindow", "MENUTEC", None))

